# Generated by Django 5.1.4 on 2025-05-18 23:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_folders', to='insurance.patientinsurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_folders', to='utilisateurs.patient')),
            ],
            options={
                'verbose_name': 'Reimbursement Folder',
                'verbose_name_plural': 'Reimbursement Folders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='reimbursement_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='insurance.reimbursementfolder')),
            ],
            options={
                'verbose_name': 'Reimbursement Document',
                'verbose_name_plural': 'Reimbursement Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
