# Generated by Django 5.1.4 on 2025-05-17 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointement',
            options={'ordering': ['-date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AddField(
            model_name='appointement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
