# Generated by Django 5.1.4 on 2025-05-17 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointements', '0002_alter_appointement_options_appointement_created_at'),
        ('invoice', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointement',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_record', to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='appointement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointement',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='utilisateurs.doctor'),
        ),
        migrations.AlterField(
            model_name='appointement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='utilisateurs.patient'),
        ),
    ]
