# Generated by Django 5.1.4 on 2025-05-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointements', '0003_appointement_invoice_appointement_updated_at_and_more'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointement',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointement',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='appointement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointement',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.doctor'),
        ),
        migrations.AlterField(
            model_name='appointement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.patient'),
        ),
    ]
