# Generated by Django 5.1.4 on 2025-05-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointements', '0004_alter_appointement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointement',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='appointement',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
